#!/bin/bash
SRCDIR=$(pwd)/ros2_ws/
xhost +local:docker
docker run -it \
    -v /var/run/dbus/:/var/run/dbus \
    -v $SRCDIR:/ros2_ws \
    -v $SRCDIR/src/brobot/src/spinPics:/spinPics \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /root/.Xauthority:/root/.Xauthority \
    --env DISPLAY=unix$DISPLAY \
    --device=/dev/ttyACM0   \
    --device=/dev/ttyACM1   \
    --net=host \
    --privileged \
    brobot $@

