#!/bin/bash
docker run -it \
    -v /var/run/dbus/:/var/run/dbus \
    -v /home/snuc/Github/BRobot/brobot/src:/source \
    -v /home/snuc/Github/BRobot/brobot/src/spinPics:/spinPics \
    --privileged \
    brobot $@
#     osrf/ros:humble-desktop-full $@
# -v /home/jcristia/Documents/GitHub/BRobot/brobot/src:/source \
