#!/bin/bash
docker run -it \
    -v /var/run/dbus/:/var/run/dbus \
    -v /home/jcristia/Documents/GitHub/BRobot/brobot/src:/source \
    --privileged \
    brobot $@
#     osrf/ros:humble-desktop-full $@

